services:
  db-test:
    image: postgres:latest
    container_name: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pomodoro
    ports:
      - "5433:5432"

  cache-test:
    image: redis:7.2.4-alpine
    restart: always
    ports:
      - '6379:6379'
